/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as StaffRouteRouteImport } from './routes/_staff/route'
import { Route as StaffIndexRouteImport } from './routes/_staff/index'
import { Route as StaffTeamRouteImport } from './routes/_staff/team'
import { Route as StaffSetupRouteImport } from './routes/_staff/setup'
import { Route as StaffSettingsRouteImport } from './routes/_staff/settings'
import { Route as StaffRolesRouteImport } from './routes/_staff/roles'
import { Route as StaffRecycleRouteImport } from './routes/_staff/recycle'
import { Route as StaffPaymentsRouteImport } from './routes/_staff/payments'
import { Route as StaffPaymentMethodsRouteImport } from './routes/_staff/payment-methods'
import { Route as StaffOrdersRouteImport } from './routes/_staff/orders'
import { Route as StaffNotificationsRouteImport } from './routes/_staff/notifications'
import { Route as StaffMobileAppRouteImport } from './routes/_staff/mobile-app'
import { Route as StaffLoginCallbackRouteImport } from './routes/_staff/login-callback'
import { Route as StaffLoginRouteImport } from './routes/_staff/login'
import { Route as StaffJoinRouteImport } from './routes/_staff/join'
import { Route as StaffInventoryRouteImport } from './routes/_staff/inventory'
import { Route as StaffInsightsRouteImport } from './routes/_staff/insights'
import { Route as StaffDeliveryRouteImport } from './routes/_staff/delivery'
import { Route as StaffCategoriesRouteImport } from './routes/_staff/categories'
import { Route as StaffAuditRouteImport } from './routes/_staff/audit'
import { Route as StaffAcceptInviteRouteImport } from './routes/_staff/accept-invite'
import { Route as StaffProductsIndexRouteImport } from './routes/_staff/products/index'
import { Route as StaffProductsNewRouteImport } from './routes/_staff/products/new'
import { Route as StaffProductsIdRouteImport } from './routes/_staff/products/$id'
import { Route as StaffOrdersIdRouteImport } from './routes/_staff/orders.$id'

const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRouteRoute = StaffRouteRouteImport.update({
  id: '/_staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffTeamRoute = StaffTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffSetupRoute = StaffSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffSettingsRoute = StaffSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffRolesRoute = StaffRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffRecycleRoute = StaffRecycleRouteImport.update({
  id: '/recycle',
  path: '/recycle',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffPaymentsRoute = StaffPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffPaymentMethodsRoute = StaffPaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffOrdersRoute = StaffOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffNotificationsRoute = StaffNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffMobileAppRoute = StaffMobileAppRouteImport.update({
  id: '/mobile-app',
  path: '/mobile-app',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffLoginCallbackRoute = StaffLoginCallbackRouteImport.update({
  id: '/login-callback',
  path: '/login-callback',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffJoinRoute = StaffJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffInventoryRoute = StaffInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffInsightsRoute = StaffInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffDeliveryRoute = StaffDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffCategoriesRoute = StaffCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffAuditRoute = StaffAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffAcceptInviteRoute = StaffAcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffProductsIndexRoute = StaffProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffProductsNewRoute = StaffProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffProductsIdRoute = StaffProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffOrdersIdRoute = StaffOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StaffIndexRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/accept-invite': typeof StaffAcceptInviteRoute
  '/audit': typeof StaffAuditRoute
  '/categories': typeof StaffCategoriesRoute
  '/delivery': typeof StaffDeliveryRoute
  '/insights': typeof StaffInsightsRoute
  '/inventory': typeof StaffInventoryRoute
  '/join': typeof StaffJoinRoute
  '/login': typeof StaffLoginRoute
  '/login-callback': typeof StaffLoginCallbackRoute
  '/mobile-app': typeof StaffMobileAppRoute
  '/notifications': typeof StaffNotificationsRoute
  '/orders': typeof StaffOrdersRouteWithChildren
  '/payment-methods': typeof StaffPaymentMethodsRoute
  '/payments': typeof StaffPaymentsRoute
  '/recycle': typeof StaffRecycleRoute
  '/roles': typeof StaffRolesRoute
  '/settings': typeof StaffSettingsRoute
  '/setup': typeof StaffSetupRoute
  '/team': typeof StaffTeamRoute
  '/orders/$id': typeof StaffOrdersIdRoute
  '/products/$id': typeof StaffProductsIdRoute
  '/products/new': typeof StaffProductsNewRoute
  '/products/': typeof StaffProductsIndexRoute
}
export interface FileRoutesByTo {
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/accept-invite': typeof StaffAcceptInviteRoute
  '/audit': typeof StaffAuditRoute
  '/categories': typeof StaffCategoriesRoute
  '/delivery': typeof StaffDeliveryRoute
  '/insights': typeof StaffInsightsRoute
  '/inventory': typeof StaffInventoryRoute
  '/join': typeof StaffJoinRoute
  '/login': typeof StaffLoginRoute
  '/login-callback': typeof StaffLoginCallbackRoute
  '/mobile-app': typeof StaffMobileAppRoute
  '/notifications': typeof StaffNotificationsRoute
  '/orders': typeof StaffOrdersRouteWithChildren
  '/payment-methods': typeof StaffPaymentMethodsRoute
  '/payments': typeof StaffPaymentsRoute
  '/recycle': typeof StaffRecycleRoute
  '/roles': typeof StaffRolesRoute
  '/settings': typeof StaffSettingsRoute
  '/setup': typeof StaffSetupRoute
  '/team': typeof StaffTeamRoute
  '/': typeof StaffIndexRoute
  '/orders/$id': typeof StaffOrdersIdRoute
  '/products/$id': typeof StaffProductsIdRoute
  '/products/new': typeof StaffProductsNewRoute
  '/products': typeof StaffProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_staff': typeof StaffRouteRouteWithChildren
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/_staff/accept-invite': typeof StaffAcceptInviteRoute
  '/_staff/audit': typeof StaffAuditRoute
  '/_staff/categories': typeof StaffCategoriesRoute
  '/_staff/delivery': typeof StaffDeliveryRoute
  '/_staff/insights': typeof StaffInsightsRoute
  '/_staff/inventory': typeof StaffInventoryRoute
  '/_staff/join': typeof StaffJoinRoute
  '/_staff/login': typeof StaffLoginRoute
  '/_staff/login-callback': typeof StaffLoginCallbackRoute
  '/_staff/mobile-app': typeof StaffMobileAppRoute
  '/_staff/notifications': typeof StaffNotificationsRoute
  '/_staff/orders': typeof StaffOrdersRouteWithChildren
  '/_staff/payment-methods': typeof StaffPaymentMethodsRoute
  '/_staff/payments': typeof StaffPaymentsRoute
  '/_staff/recycle': typeof StaffRecycleRoute
  '/_staff/roles': typeof StaffRolesRoute
  '/_staff/settings': typeof StaffSettingsRoute
  '/_staff/setup': typeof StaffSetupRoute
  '/_staff/team': typeof StaffTeamRoute
  '/_staff/': typeof StaffIndexRoute
  '/_staff/orders/$id': typeof StaffOrdersIdRoute
  '/_staff/products/$id': typeof StaffProductsIdRoute
  '/_staff/products/new': typeof StaffProductsNewRoute
  '/_staff/products/': typeof StaffProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manifest.webmanifest'
    | '/accept-invite'
    | '/audit'
    | '/categories'
    | '/delivery'
    | '/insights'
    | '/inventory'
    | '/join'
    | '/login'
    | '/login-callback'
    | '/mobile-app'
    | '/notifications'
    | '/orders'
    | '/payment-methods'
    | '/payments'
    | '/recycle'
    | '/roles'
    | '/settings'
    | '/setup'
    | '/team'
    | '/orders/$id'
    | '/products/$id'
    | '/products/new'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/manifest.webmanifest'
    | '/accept-invite'
    | '/audit'
    | '/categories'
    | '/delivery'
    | '/insights'
    | '/inventory'
    | '/join'
    | '/login'
    | '/login-callback'
    | '/mobile-app'
    | '/notifications'
    | '/orders'
    | '/payment-methods'
    | '/payments'
    | '/recycle'
    | '/roles'
    | '/settings'
    | '/setup'
    | '/team'
    | '/'
    | '/orders/$id'
    | '/products/$id'
    | '/products/new'
    | '/products'
  id:
    | '__root__'
    | '/_staff'
    | '/manifest.webmanifest'
    | '/_staff/accept-invite'
    | '/_staff/audit'
    | '/_staff/categories'
    | '/_staff/delivery'
    | '/_staff/insights'
    | '/_staff/inventory'
    | '/_staff/join'
    | '/_staff/login'
    | '/_staff/login-callback'
    | '/_staff/mobile-app'
    | '/_staff/notifications'
    | '/_staff/orders'
    | '/_staff/payment-methods'
    | '/_staff/payments'
    | '/_staff/recycle'
    | '/_staff/roles'
    | '/_staff/settings'
    | '/_staff/setup'
    | '/_staff/team'
    | '/_staff/'
    | '/_staff/orders/$id'
    | '/_staff/products/$id'
    | '/_staff/products/new'
    | '/_staff/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StaffRouteRoute: typeof StaffRouteRouteWithChildren
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff': {
      id: '/_staff'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StaffRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff/': {
      id: '/_staff/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/team': {
      id: '/_staff/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof StaffTeamRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/setup': {
      id: '/_staff/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof StaffSetupRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/settings': {
      id: '/_staff/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof StaffSettingsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/roles': {
      id: '/_staff/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof StaffRolesRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/recycle': {
      id: '/_staff/recycle'
      path: '/recycle'
      fullPath: '/recycle'
      preLoaderRoute: typeof StaffRecycleRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/payments': {
      id: '/_staff/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof StaffPaymentsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/payment-methods': {
      id: '/_staff/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof StaffPaymentMethodsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/orders': {
      id: '/_staff/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof StaffOrdersRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/notifications': {
      id: '/_staff/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof StaffNotificationsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/mobile-app': {
      id: '/_staff/mobile-app'
      path: '/mobile-app'
      fullPath: '/mobile-app'
      preLoaderRoute: typeof StaffMobileAppRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/login-callback': {
      id: '/_staff/login-callback'
      path: '/login-callback'
      fullPath: '/login-callback'
      preLoaderRoute: typeof StaffLoginCallbackRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/login': {
      id: '/_staff/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/join': {
      id: '/_staff/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof StaffJoinRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/inventory': {
      id: '/_staff/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof StaffInventoryRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/insights': {
      id: '/_staff/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof StaffInsightsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/delivery': {
      id: '/_staff/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof StaffDeliveryRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/categories': {
      id: '/_staff/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof StaffCategoriesRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/audit': {
      id: '/_staff/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof StaffAuditRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/accept-invite': {
      id: '/_staff/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof StaffAcceptInviteRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/products/': {
      id: '/_staff/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof StaffProductsIndexRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/products/new': {
      id: '/_staff/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof StaffProductsNewRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/products/$id': {
      id: '/_staff/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof StaffProductsIdRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/orders/$id': {
      id: '/_staff/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof StaffOrdersIdRouteImport
      parentRoute: typeof StaffOrdersRoute
    }
  }
}

interface StaffOrdersRouteChildren {
  StaffOrdersIdRoute: typeof StaffOrdersIdRoute
}

const StaffOrdersRouteChildren: StaffOrdersRouteChildren = {
  StaffOrdersIdRoute: StaffOrdersIdRoute,
}

const StaffOrdersRouteWithChildren = StaffOrdersRoute._addFileChildren(
  StaffOrdersRouteChildren,
)

interface StaffRouteRouteChildren {
  StaffAcceptInviteRoute: typeof StaffAcceptInviteRoute
  StaffAuditRoute: typeof StaffAuditRoute
  StaffCategoriesRoute: typeof StaffCategoriesRoute
  StaffDeliveryRoute: typeof StaffDeliveryRoute
  StaffInsightsRoute: typeof StaffInsightsRoute
  StaffInventoryRoute: typeof StaffInventoryRoute
  StaffJoinRoute: typeof StaffJoinRoute
  StaffLoginRoute: typeof StaffLoginRoute
  StaffLoginCallbackRoute: typeof StaffLoginCallbackRoute
  StaffMobileAppRoute: typeof StaffMobileAppRoute
  StaffNotificationsRoute: typeof StaffNotificationsRoute
  StaffOrdersRoute: typeof StaffOrdersRouteWithChildren
  StaffPaymentMethodsRoute: typeof StaffPaymentMethodsRoute
  StaffPaymentsRoute: typeof StaffPaymentsRoute
  StaffRecycleRoute: typeof StaffRecycleRoute
  StaffRolesRoute: typeof StaffRolesRoute
  StaffSettingsRoute: typeof StaffSettingsRoute
  StaffSetupRoute: typeof StaffSetupRoute
  StaffTeamRoute: typeof StaffTeamRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StaffProductsIdRoute: typeof StaffProductsIdRoute
  StaffProductsNewRoute: typeof StaffProductsNewRoute
  StaffProductsIndexRoute: typeof StaffProductsIndexRoute
}

const StaffRouteRouteChildren: StaffRouteRouteChildren = {
  StaffAcceptInviteRoute: StaffAcceptInviteRoute,
  StaffAuditRoute: StaffAuditRoute,
  StaffCategoriesRoute: StaffCategoriesRoute,
  StaffDeliveryRoute: StaffDeliveryRoute,
  StaffInsightsRoute: StaffInsightsRoute,
  StaffInventoryRoute: StaffInventoryRoute,
  StaffJoinRoute: StaffJoinRoute,
  StaffLoginRoute: StaffLoginRoute,
  StaffLoginCallbackRoute: StaffLoginCallbackRoute,
  StaffMobileAppRoute: StaffMobileAppRoute,
  StaffNotificationsRoute: StaffNotificationsRoute,
  StaffOrdersRoute: StaffOrdersRouteWithChildren,
  StaffPaymentMethodsRoute: StaffPaymentMethodsRoute,
  StaffPaymentsRoute: StaffPaymentsRoute,
  StaffRecycleRoute: StaffRecycleRoute,
  StaffRolesRoute: StaffRolesRoute,
  StaffSettingsRoute: StaffSettingsRoute,
  StaffSetupRoute: StaffSetupRoute,
  StaffTeamRoute: StaffTeamRoute,
  StaffIndexRoute: StaffIndexRoute,
  StaffProductsIdRoute: StaffProductsIdRoute,
  StaffProductsNewRoute: StaffProductsNewRoute,
  StaffProductsIndexRoute: StaffProductsIndexRoute,
}

const StaffRouteRouteWithChildren = StaffRouteRoute._addFileChildren(
  StaffRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  StaffRouteRoute: StaffRouteRouteWithChildren,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
