/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as HealthDotjsonRouteImport } from './routes/health[.]json'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as OrderReferenceRouteImport } from './routes/order.$reference'
import { Route as AccountSignupRouteImport } from './routes/account.signup'
import { Route as AccountLoginRouteImport } from './routes/account.login'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthDotjsonRoute = HealthDotjsonRouteImport.update({
  id: '/health.json',
  path: '/health.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderReferenceRoute = OrderReferenceRouteImport.update({
  id: '/order/$reference',
  path: '/order/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSignupRoute = AccountSignupRouteImport.update({
  id: '/account/signup',
  path: '/account/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/health.json': typeof HealthDotjsonRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/orders': typeof OrdersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/account/login': typeof AccountLoginRoute
  '/account/signup': typeof AccountSignupRoute
  '/order/$reference': typeof OrderReferenceRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/health.json': typeof HealthDotjsonRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/orders': typeof OrdersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/account/login': typeof AccountLoginRoute
  '/account/signup': typeof AccountSignupRoute
  '/order/$reference': typeof OrderReferenceRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account': typeof AccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/health.json': typeof HealthDotjsonRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/orders': typeof OrdersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/account/login': typeof AccountLoginRoute
  '/account/signup': typeof AccountSignupRoute
  '/order/$reference': typeof OrderReferenceRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/health.json'
    | '/manifest.webmanifest'
    | '/orders'
    | '/robots.txt'
    | '/shop'
    | '/sitemap.xml'
    | '/wishlist'
    | '/account/login'
    | '/account/signup'
    | '/order/$reference'
    | '/product/$slug'
    | '/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/health.json'
    | '/manifest.webmanifest'
    | '/orders'
    | '/robots.txt'
    | '/shop'
    | '/sitemap.xml'
    | '/wishlist'
    | '/account/login'
    | '/account/signup'
    | '/order/$reference'
    | '/product/$slug'
    | '/account'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/health.json'
    | '/manifest.webmanifest'
    | '/orders'
    | '/robots.txt'
    | '/shop'
    | '/sitemap.xml'
    | '/wishlist'
    | '/account/login'
    | '/account/signup'
    | '/order/$reference'
    | '/product/$slug'
    | '/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  HealthDotjsonRoute: typeof HealthDotjsonRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  OrdersRoute: typeof OrdersRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WishlistRoute: typeof WishlistRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountSignupRoute: typeof AccountSignupRoute
  OrderReferenceRoute: typeof OrderReferenceRoute
  ProductSlugRoute: typeof ProductSlugRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health.json': {
      id: '/health.json'
      path: '/health.json'
      fullPath: '/health.json'
      preLoaderRoute: typeof HealthDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$reference': {
      id: '/order/$reference'
      path: '/order/$reference'
      fullPath: '/order/$reference'
      preLoaderRoute: typeof OrderReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/signup': {
      id: '/account/signup'
      path: '/account/signup'
      fullPath: '/account/signup'
      preLoaderRoute: typeof AccountSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/login': {
      id: '/account/login'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  HealthDotjsonRoute: HealthDotjsonRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  OrdersRoute: OrdersRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WishlistRoute: WishlistRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountSignupRoute: AccountSignupRoute,
  OrderReferenceRoute: OrderReferenceRoute,
  ProductSlugRoute: ProductSlugRoute,
  AccountIndexRoute: AccountIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
