/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as HealthDotjsonRouteImport } from './routes/health[.]json'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminManifestDotwebmanifestRouteImport } from './routes/admin-manifest[.]webmanifest'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as OrderReferenceRouteImport } from './routes/order.$reference'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminSignupRouteImport } from './routes/admin.signup'
import { Route as AdminSetupRouteImport } from './routes/admin.setup'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminRecycleRouteImport } from './routes/admin.recycle'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPaymentMethodsRouteImport } from './routes/admin.payment-methods'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMobileAppRouteImport } from './routes/admin.mobile-app'
import { Route as AdminLoginCallbackRouteImport } from './routes/admin.login-callback'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminJoinRouteImport } from './routes/admin.join'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminInsightsRouteImport } from './routes/admin.insights'
import { Route as AdminDeliveryRouteImport } from './routes/admin.delivery'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAccountRouteImport } from './routes/admin.account'
import { Route as AdminAcceptInviteRouteImport } from './routes/admin.accept-invite'
import { Route as AccountSignupRouteImport } from './routes/account.signup'
import { Route as AccountLoginRouteImport } from './routes/account.login'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminRRoleRouteImport } from './routes/admin.r.$role'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as AdminProductsIdRouteImport } from './routes/admin.products.$id'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthDotjsonRoute = HealthDotjsonRouteImport.update({
  id: '/health.json',
  path: '/health.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManifestDotwebmanifestRoute =
  AdminManifestDotwebmanifestRouteImport.update({
    id: '/admin-manifest.webmanifest',
    path: '/admin-manifest.webmanifest',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderReferenceRoute = OrderReferenceRouteImport.update({
  id: '/order/$reference',
  path: '/order/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSignupRoute = AdminSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecycleRoute = AdminRecycleRouteImport.update({
  id: '/recycle',
  path: '/recycle',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentMethodsRoute = AdminPaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMobileAppRoute = AdminMobileAppRouteImport.update({
  id: '/mobile-app',
  path: '/mobile-app',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginCallbackRoute = AdminLoginCallbackRouteImport.update({
  id: '/login-callback',
  path: '/login-callback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJoinRoute = AdminJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInsightsRoute = AdminInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveryRoute = AdminDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcceptInviteRoute = AdminAcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => AdminRoute,
} as any)
const AccountSignupRoute = AccountSignupRouteImport.update({
  id: '/account/signup',
  path: '/account/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRRoleRoute = AdminRRoleRouteImport.update({
  id: '/r/$role',
  path: '/r/$role',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-manifest.webmanifest': typeof AdminManifestDotwebmanifestRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/health.json': typeof HealthDotjsonRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/orders': typeof OrdersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/account/login': typeof AccountLoginRoute
  '/account/signup': typeof AccountSignupRoute
  '/admin/accept-invite': typeof AdminAcceptInviteRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/join': typeof AdminJoinRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/login-callback': typeof AdminLoginCallbackRoute
  '/admin/mobile-app': typeof AdminMobileAppRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/recycle': typeof AdminRecycleRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/team': typeof AdminTeamRoute
  '/order/$reference': typeof OrderReferenceRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/r/$role': typeof AdminRRoleRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-manifest.webmanifest': typeof AdminManifestDotwebmanifestRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/health.json': typeof HealthDotjsonRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/orders': typeof OrdersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/account/login': typeof AccountLoginRoute
  '/account/signup': typeof AccountSignupRoute
  '/admin/accept-invite': typeof AdminAcceptInviteRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/join': typeof AdminJoinRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/login-callback': typeof AdminLoginCallbackRoute
  '/admin/mobile-app': typeof AdminMobileAppRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/recycle': typeof AdminRecycleRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/team': typeof AdminTeamRoute
  '/order/$reference': typeof OrderReferenceRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/r/$role': typeof AdminRRoleRoute
  '/admin/products': typeof AdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-manifest.webmanifest': typeof AdminManifestDotwebmanifestRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/health.json': typeof HealthDotjsonRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/orders': typeof OrdersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/account/login': typeof AccountLoginRoute
  '/account/signup': typeof AccountSignupRoute
  '/admin/accept-invite': typeof AdminAcceptInviteRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/join': typeof AdminJoinRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/login-callback': typeof AdminLoginCallbackRoute
  '/admin/mobile-app': typeof AdminMobileAppRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/recycle': typeof AdminRecycleRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/team': typeof AdminTeamRoute
  '/order/$reference': typeof OrderReferenceRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/r/$role': typeof AdminRRoleRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-manifest.webmanifest'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/health.json'
    | '/manifest.webmanifest'
    | '/orders'
    | '/robots.txt'
    | '/shop'
    | '/sitemap.xml'
    | '/wishlist'
    | '/account/login'
    | '/account/signup'
    | '/admin/accept-invite'
    | '/admin/account'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/delivery'
    | '/admin/insights'
    | '/admin/inventory'
    | '/admin/join'
    | '/admin/login'
    | '/admin/login-callback'
    | '/admin/mobile-app'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payment-methods'
    | '/admin/payments'
    | '/admin/recycle'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/signup'
    | '/admin/team'
    | '/order/$reference'
    | '/product/$slug'
    | '/account/'
    | '/admin/'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/r/$role'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-manifest.webmanifest'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/health.json'
    | '/manifest.webmanifest'
    | '/orders'
    | '/robots.txt'
    | '/shop'
    | '/sitemap.xml'
    | '/wishlist'
    | '/account/login'
    | '/account/signup'
    | '/admin/accept-invite'
    | '/admin/account'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/delivery'
    | '/admin/insights'
    | '/admin/inventory'
    | '/admin/join'
    | '/admin/login'
    | '/admin/login-callback'
    | '/admin/mobile-app'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payment-methods'
    | '/admin/payments'
    | '/admin/recycle'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/signup'
    | '/admin/team'
    | '/order/$reference'
    | '/product/$slug'
    | '/account'
    | '/admin'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/r/$role'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-manifest.webmanifest'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/health.json'
    | '/manifest.webmanifest'
    | '/orders'
    | '/robots.txt'
    | '/shop'
    | '/sitemap.xml'
    | '/wishlist'
    | '/account/login'
    | '/account/signup'
    | '/admin/accept-invite'
    | '/admin/account'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/delivery'
    | '/admin/insights'
    | '/admin/inventory'
    | '/admin/join'
    | '/admin/login'
    | '/admin/login-callback'
    | '/admin/mobile-app'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payment-methods'
    | '/admin/payments'
    | '/admin/recycle'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/signup'
    | '/admin/team'
    | '/order/$reference'
    | '/product/$slug'
    | '/account/'
    | '/admin/'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/r/$role'
    | '/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminManifestDotwebmanifestRoute: typeof AdminManifestDotwebmanifestRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  HealthDotjsonRoute: typeof HealthDotjsonRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  OrdersRoute: typeof OrdersRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WishlistRoute: typeof WishlistRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountSignupRoute: typeof AccountSignupRoute
  OrderReferenceRoute: typeof OrderReferenceRoute
  ProductSlugRoute: typeof ProductSlugRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health.json': {
      id: '/health.json'
      path: '/health.json'
      fullPath: '/health.json'
      preLoaderRoute: typeof HealthDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-manifest.webmanifest': {
      id: '/admin-manifest.webmanifest'
      path: '/admin-manifest.webmanifest'
      fullPath: '/admin-manifest.webmanifest'
      preLoaderRoute: typeof AdminManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$reference': {
      id: '/order/$reference'
      path: '/order/$reference'
      fullPath: '/order/$reference'
      preLoaderRoute: typeof OrderReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/signup': {
      id: '/admin/signup'
      path: '/signup'
      fullPath: '/admin/signup'
      preLoaderRoute: typeof AdminSignupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recycle': {
      id: '/admin/recycle'
      path: '/recycle'
      fullPath: '/admin/recycle'
      preLoaderRoute: typeof AdminRecycleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payment-methods': {
      id: '/admin/payment-methods'
      path: '/payment-methods'
      fullPath: '/admin/payment-methods'
      preLoaderRoute: typeof AdminPaymentMethodsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mobile-app': {
      id: '/admin/mobile-app'
      path: '/mobile-app'
      fullPath: '/admin/mobile-app'
      preLoaderRoute: typeof AdminMobileAppRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login-callback': {
      id: '/admin/login-callback'
      path: '/login-callback'
      fullPath: '/admin/login-callback'
      preLoaderRoute: typeof AdminLoginCallbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/join': {
      id: '/admin/join'
      path: '/join'
      fullPath: '/admin/join'
      preLoaderRoute: typeof AdminJoinRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/insights': {
      id: '/admin/insights'
      path: '/insights'
      fullPath: '/admin/insights'
      preLoaderRoute: typeof AdminInsightsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/delivery': {
      id: '/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminDeliveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accept-invite': {
      id: '/admin/accept-invite'
      path: '/accept-invite'
      fullPath: '/admin/accept-invite'
      preLoaderRoute: typeof AdminAcceptInviteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/signup': {
      id: '/account/signup'
      path: '/account/signup'
      fullPath: '/account/signup'
      preLoaderRoute: typeof AccountSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/login': {
      id: '/account/login'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/r/$role': {
      id: '/admin/r/$role'
      path: '/r/$role'
      fullPath: '/admin/r/$role'
      preLoaderRoute: typeof AdminRRoleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
  }
}

interface AdminOrdersRouteChildren {
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIdRoute: AdminOrdersIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminRouteChildren {
  AdminAcceptInviteRoute: typeof AdminAcceptInviteRoute
  AdminAccountRoute: typeof AdminAccountRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDeliveryRoute: typeof AdminDeliveryRoute
  AdminInsightsRoute: typeof AdminInsightsRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminJoinRoute: typeof AdminJoinRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLoginCallbackRoute: typeof AdminLoginCallbackRoute
  AdminMobileAppRoute: typeof AdminMobileAppRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminPaymentMethodsRoute: typeof AdminPaymentMethodsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminRecycleRoute: typeof AdminRecycleRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminSignupRoute: typeof AdminSignupRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminRRoleRoute: typeof AdminRRoleRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAcceptInviteRoute: AdminAcceptInviteRoute,
  AdminAccountRoute: AdminAccountRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDeliveryRoute: AdminDeliveryRoute,
  AdminInsightsRoute: AdminInsightsRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminJoinRoute: AdminJoinRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLoginCallbackRoute: AdminLoginCallbackRoute,
  AdminMobileAppRoute: AdminMobileAppRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminPaymentMethodsRoute: AdminPaymentMethodsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminRecycleRoute: AdminRecycleRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminSignupRoute: AdminSignupRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminRRoleRoute: AdminRRoleRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminManifestDotwebmanifestRoute: AdminManifestDotwebmanifestRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  HealthDotjsonRoute: HealthDotjsonRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  OrdersRoute: OrdersRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WishlistRoute: WishlistRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountSignupRoute: AccountSignupRoute,
  OrderReferenceRoute: OrderReferenceRoute,
  ProductSlugRoute: ProductSlugRoute,
  AccountIndexRoute: AccountIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
